### ISSUE TITLE
add small X to div popup to allow users to close popup

### ISSUE THREAD

**Issue by amyxzhang** [haystack/eyebrowse-chrome-ext#12]
useful if you really just want to click something under the popup, so want to quickly get rid of it instead of wait for it to fade.

**Comment by joshblum** [comment]
+1

**Comment by joshblum** [comment]
closed by 94d552d83b2be45a7292a72739e86a463eccb979

**Comment by amyxzhang** [comment]
can we add this for the little bubble popups too? bc sometimes they don't fade (as mentioned in #11) also they're often over navigation stuff and can be annoying.
