### ISSUE TITLE
whitelist link in click-eye popup no longer works

### ISSUE THREAD

**Issue by amyxzhang** [haystack/eyebrowse-chrome-ext#16]
now getting a URI is not defined error. popup.js line 517

**Comment by joshblum** [comment]
Whoops I'll take a look tonight

**Comment by joshblum** [comment]
closed by 82ed27c042d9b184b54c0ceb8e545f2ada776cb4

**Comment by amyxzhang** [comment]
Hm still seems to be a problem for me. I tried to update the dev store with the latest code.
Also, the little popup asking if I want to whitelist a page doesn't seem to be working either. I click Yes but nothing happens. and a few seconds later I get the popup again and again.... seems like our nagging backoff is also not working as expected? As a sort of aside, some feedback I've gotten from other people is that nags happen way too often (shouldn't appear on *every* non-whitelist/blacklist webpage, only some). maybe set an absolute # of nags for every 15 minute (like 1) or something like that.

**Comment by amyxzhang** [comment]
clicking No in the nag popup also doesn't seem to add it my blacklist (on the client side or on the server)

**Comment by joshblum** [comment]
agreed for the nag#. is this still happening with the update?

**Comment by joshblum** [comment]
closing this but leaving #21 open
