### ISSUE TITLE
sometimes my whitelist and blacklist seems to be lost

### ISSUE THREAD

**Issue by amyxzhang** [haystack/eyebrowse-chrome-ext#18]
sometimes (often) when I log out and log back in, my whitelist and blacklist become empty.

**Comment by joshblum** [comment]
are there any errors in `background.html` when this happens?

**Comment by amyxzhang** [comment]
hm wasn't able to reproduce just now. the issue seemed to be coming up when I was logging out of one account and then logging in to another account. I think what was happening was that the white and blacklists were not updating right away.

so my 2nd acct has no whitelists. and yet it sent an eyehistory when I logged out of my main acct into the 2nd acct when I was on a page whitelisted by my main acct. closing and opening the popup fixed the issue so that it said "Whitelist this domain" properly, but the visit had already gone through to the server.

I don't think this is a huge issue so I would prefer to put it on the back burner. Since most ppl won't be dealing with multiple accts for now.

If I see an issue where my white and black lists are not correct in another context (not switching accounts) I will mark it here.

**Comment by joshblum** [comment]
ok i'll close this for now but we can reopen if it pops up.

can you double check that the item never made it through the server? regardless of what the client sends the server does whitelist checking so if the history item was actually logged that's a bigger issue..
