### ISSUE TITLE
the first time I go to a page and try to type a message, nothing happens

### ISSUE THREAD

**Issue by amyxzhang** [haystack/eyebrowse-chrome-ext#19]
seems to fail silently. 

then when I click open the popup again, and type a note, the 2nd time works.
Not sure what's going on but this has happened to me twice now.

**Comment by joshblum** [comment]
hmm i can't seem to reproduce. any errors in `background.html` or `popup.html`?

**Comment by amyxzhang** [comment]
just tried it just now and it worked fine. but I also got this error:

popup.js:794 Uncaught TypeError: undefined is not a function

**Comment by joshblum** [comment]
whoops had a silly bug: ddf524387ee7ace93042ddec3234affed05cf4a5
