### ISSUE TITLE
Chrome extension sometimes leaves behind an invisible box in the top right corner

### ISSUE THREAD

**Issue by qqliu** [haystack/eyebrowse-chrome-ext#2]
The Chrome extension sometimes leaves a clear box on the top right of the screen when it pops out. This issue is sometimes reproducibles, other times not. I'm not quite sure what produces it. I most often encounter it when I first start a Chrome page (so it doesn't occur only when I click on the icon.) Here are a few screenshots of what happens and its effects.

![screen shot 2014-03-05 at 2 19 52 pm](https://f.cloud.github.com/assets/1966369/2337105/5e4614e2-a499-11e3-9619-994d6d839079.png)

![screen shot 2014-03-05 at 2 21 39 pm](https://f.cloud.github.com/assets/1966369/2337125/9ebfc914-a499-11e3-8ebd-88a6a22e466a.png)

The first is produced when the page was started. And the second is what happens when I delete the html elements in my chrome browser. I am running on Version 33.0.1750.146.

**Comment by joshblum** [comment]
@amyxzhang This should be completed yeah?

**Comment by amyxzhang** [comment]
yeah
