### ISSUE TITLE
logging out via the website used to create a small div that said "You've logged out...etc"

### ISSUE THREAD

**Issue by amyxzhang** [haystack/eyebrowse-chrome-ext#20]
now no longer appears - there's just that ! tag by the eye.

**Comment by joshblum** [comment]
hmm i get the login screen when the "!" appears on the icon. Where was the div?

**Comment by amyxzhang** [comment]
Oh it was similar looking to the nag (not when you click the icon) so it
was injected into the page on the too right as a div.

On Monday, March 23, 2015, Joshua Blum <notifications@github.com> wrote:

> hmm i get the login screen when the "!" appears on the icon. Where was the
> div?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/haystack/eyebrowse-chrome-ext/issues/20#issuecomment-85240229>
> .
>


-- 
Amy X. Zhang | Ph.D. student at MIT CSAIL | http://people.csail.mit.edu/axz
| @amyxzh

**Comment by joshblum** [comment]
should be fixed by 83edab11b3729e4fd7b395537b6bac2a7d39f4b0
