### ISSUE TITLE
Bug with nagging + set nag limit

### ISSUE THREAD

**Issue by joshblum** [haystack/eyebrowse-chrome-ext#21]
Doesn't seem to be working properly

**Comment by joshblum** [comment]
@amyxzhang i think the problem was related to the keys we were setting in the `nags` hashmap. can you checkout locally and verify the bug is done? e358caf0ad1a7e55802c03e23c11f697a068b4e7

Regarding the nag code I kinda of like the model of either triggering a nag after a number of visits or a time threshold, perhaps we should just increase the number of overall visits required?(https://github.com/haystack/eyebrowse-chrome-ext/blob/master/js/main.js#L268)

**Comment by karger** [comment]
Agreed on a minimum threshold for nags.  Or more generally, to not nag 
about "unimportant" sites if you are expecting to encounter and want to 
nag about important ones.  But how do we know if you're going to 
encounter a more important site?  Here's one heuristic: once you've 
decided it's time to nag, and nag about a site, allow yourself to nag 
about any "more important" site that is encountered thereafter (and then 
to nag about any site more important than that, etc.).  Each time you 
nag the importance threshold will go up, so you're unlikely to do too 
many nags.

**Comment by amyxzhang** [comment]
I think we can do that (increase the visits for now) and we can re-evaluate later? I personally haven't found it to be bad but maybe I've white and blacklisted a lot of sites by now.

**Comment by amyxzhang** [comment]
just tried it out locally and it looks good to me.

**Comment by joshblum** [comment]
sweet. closing this, bumped up the limit to 15 visits before a nag (or if an hour has passed) with a10c2efb8305a2408fea0081622b6f5366f462d5 we can tweak as necessary
