### ISSUE TITLE
add small X to bubble popup

### ISSUE THREAD

**Issue by joshblum** [haystack/eyebrowse-chrome-ext#22]

**Comment by joshblum** [comment]
closed by 4b686669778f478535e565edd52df9921db6e975

**Comment by amyxzhang** [comment]
Clicking on them doesn't seem to close anything for me in production.

**Comment by amyxzhang** [comment]
Actually it does seem to work most times, but now and then it doesn't work for me. And it seems to change even on the same site. *sigh* I'll let you know if I find out anything more concrete.
