### ISSUE TITLE
Constantly asking to track localhost.

### ISSUE THREAD

**Issue by Stebalien** [haystack/eyebrowse-chrome-ext#4]
I'm working on a project and running it on 'http://localhost:8080' and eyebrowse keeps on asking if I want to publish my history for localhost.
  1. It should blacklist all domains not ending in public TLDs (this will also catch certain intranet systems).
  2. It shouldn't keep on asking for permission (this is probably happening because it expects domains to be in the form 'a.b').

**Comment by amyxzhang** [comment]
some people are indeed whitelisting their localhost activity. dunno if this is something we want to continue allowing or no.

2 is still def an issue.

**Comment by joshblum** [comment]
2. should be easy to fix we need to check URLs for ports.. what do we want to do about 1.?

**Comment by karger** [comment]
arguably localhost is useful only for the original user since it doesn't resolve right elsewhere.  so maybe we should auto-blacklist.  counter argument is for users doing quantified self.  But is there really any point for them to track localhost?  I suspect most people whitelisting localhost are just answering yes to the nag---not because they really want to but because they don't care.

**Comment by joshblum** [comment]
agreed about localhost. we should still parse correctly for ports since you can be working on a dev server that isn't on port 80 and the constant nagging will be irritating

**Comment by karger** [comment]
1.  if we black list localhost then we don't need to worry about nagging 
any ports at all
2.  ignoring port in whitelist is tempting, but is it always safe? 
probably, so long as there is some way to override and whitelist only a 
specific port.

**Comment by joshblum** [comment]
Even with a localhost blacklist I often develop on a server and use a nonstadard port so only blacklisting won't solve this. I think the cleanest way would be just to include a column for port # and then we don't have to add extra explicit functionality for whitelisting a specific port

**Comment by joshblum** [comment]
should be fixed by: 3d1932b32e9bece7b2fd6b839455ff6222d4870d
