### ISSUE TITLE
Excessive calls to `/ext/loggedIn`

### ISSUE THREAD

**Issue by joshblum** [haystack/eyebrowse-chrome-ext#9]
Happens a bunch of times, should store this locally and only reset if a request fails for auth reasons

**Comment by joshblum** [comment]
hmm problem seems to be with the `checkLoggedIn` function.
@amyxzhang is there a reason to call the server every time you call `openItem` vs using the stored `loggedIn` flag on the `user` object?

**Comment by amyxzhang** [comment]
right, i wanted it to update when the user logged in or out via the website. Could that be done by setting a cookie or something that the extension can then access? I couldn't figure out a way for the extension to access any non-extension data.

**Comment by joshblum** [comment]
I need to check into it but I think the extension already has access to cookies for the eyebrowse domain. I'll verify

**Comment by joshblum** [comment]
Changed a bunch of logic related to login so now we don't have to call the server every time we want to perform an action. Closed by 345dfa49d027aa07d814017ea2048e0d147d6454

**Comment by amyxzhang** [comment]
When you click logout on the extension window, you get logged out but the login window doesn't show up this time. Instead, it's just the logged in view but with everything broken/empty. I had to click logout a second time to get the login window to show up.

**Comment by joshblum** [comment]
I just tried and can't replicate :( maybe there were some other errors related to #13 that were messing things up?

**Comment by amyxzhang** [comment]
yes! it's broken in production but it looks like your latest changes fixed it!
